### ISSUE TITLE
Doesn't work with current beta

### ISSUE THREAD

**Issue by seriosbrad** [axelderoeck/custom-steam#1]
Been scouring Google to remove just the "what's new" section and stumbled upon your skin with a lot of extra tweaks I'd also like to try,  it appears that the Steam beta doesn't load any of your modifications, any idea what Valve changed?

**Comment by axelderoeck** [comment]
I haven't tried this skin with the Steam beta I will start looking into it for you soon.

**Comment by axelderoeck** [comment]
It seems like the beta is not loading the webkit.css file on the library page. The changes do work on the other pages. If the webkit.css doesn't get loaded in I sadly don't see a way this could be fixed besides extra tinkering with the local client files (css/library.css) and some extra tools.

The intention of this project was to hide as much annoyances as possible without the extra tinkering for an easy setup so I'm afraid I can't help you anymore. I could say to switch back to the normal Steam but I'm sure you have your reasons for using the beta.

On that note I will keep this issue in mind if there is any solution discovered later on. Thanks for pointing it out to me though.

**Comment by KaylaSolace** [comment]
looks like steam's stable build is rolling out a change to not load webkit.css anymore, was in the middle of editing mine, and then steam updated, and now skins don't load them anymore. RIP my purple library page.

**Comment by axelderoeck** [comment]
I just checked my own library page and indeed the What's New section is back again. This is very unfortunate news.

**Comment by KaylaSolace** [comment]
I would try using steam oldglory or whatever, but it's css tweaks break the library page in many cosmetic but annoying ways and it's just not worth it lolI liked the simplicity of my 10 line css file :/On Feb 3, 2023, at 04:49, Axel De Roeck ***@***.***> wrote:﻿
I just checked my own library page and indeed the What's New section is back again. This is very unfortunate news.
